### ISSUE TITLE
How to run the simplest and fastest test case?

### ISSUE THREAD

**Issue by dlg0** [compxco/genray#6]
How do I run the simplest and fastest test case? And what are the outputs?

@ypetrov

**Comment by dlg0** [comment]
OK, here is what I have tried so far ...

```
cd 00_Genray_Regression_Tests
mkdir test-CMod-LH-edge
cp genray.in_CMod_LH_edge test-CMod-LH-edge/genray.in
cd test-CMod-LH-edge
../../xgenray
```
but i get the following error ...
```
 N_DIM_RADII_F_PLOTS=2          ,
 N_RADII_F_PLOTS_AR=100        ,133        , 199*0          ,
 /
 in prepare_genray_input.f end reading genray.in file
 genray.f after read_all_namelists ndim            6
 in genray.f genray_in_dat=genray.in
 genray.f after read_all_ prmt    0.0000000000000000        999900.00000000000        1.0000000000000000E-002   4.9999999999999998E-007   0.0000000000000000        1.0000000000000000E-002   0.0000000000000000        0.0000000000000000        1000000000000000.0
 genray.f after read_all_ ioxm          -1
 genray.f after read_all_ nray           0
 genray.f after read_all_namelists data in /genr/
 r0x=   1.0000000000000000
 b0=   1.0000000000000000
 outdat=zrn.dat
 stat=new
 mnemonic=genray
 rayop=both
 dielectric_op=enabled
 partner=disabled
 in ainalloc before ainalloc_adj_no_nml_i
 eqdskin= g1060728011.01100
At line 288 of file equilib.f (unit = 30, file = 'g1060728011.01100')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7fe1666c470d in ???
#1  0x7fe1666c5235 in ???
#2  0x7fe1666c5c9b in ???
#3  0x7fe1668eb37d in ???
#4  0x55d3506d1bc3 in ???
#5  0x55d3506d43a8 in ???
#6  0x55d35060ed0b in ???
#7  0x55d35060ade8 in ???
#8  0x7fe165d1fb96 in ???
#9  0x55d35060ae19 in ???
#10  0xffffffffffffffff in ???
```
Am I doing something sensible?
@ypetrov

**Comment by dlg0** [comment]
Nevermind, figured it out. Need to copy across the eqdsk file too. Genray should throw useful errors about missing files. I'll make an issue. 

```
cd 00_Genray_Regression_Tests
mkdir test-CMod-LH-edge
cd test-CMod-LH-edge
cp ../genray.in_CMod_LH_edge genray.in
cp ../g1060728011.01100 .
../../xgenray
```
